### ISSUE TITLE
Adapter

### ISSUE THREAD

**Issue by toncho11** [eyalabraham/ps2kbd#1]
Hi,

I defective 74S74N chip at position U70 on my IBM 5160 motherboard. I can not replace it.

I am interested how did you connect to the 8255 of the motherboard.
https://sites.google.com/site/eyalabraham/pc-xt/ps2-keyboard?authuser=0
I would like to re-create your adapter.

I want to bypass the 74S74N by directly accessing the 8255.

**Comment by eyalabraham** [comment]
@toncho11 I updated my web pages to include the schematics of the little AVR interface board. This is the link to the schematics in PDF format: https://drive.google.com/open?id=1QVsr-YqET7IS3OkbXL5nL0MswGvEFy1h

There is also a hack that I had to do on the motherboard, which you may or may not prefer to do. The hack is:
1. Remove U35 - 74LS322 - the keyboard input shift register
2. 16-pin ribbon cable inserts into above socket starting in pin 3 - NOT pin 1
3. Raise U52 - 74LS74 - with a regular socket and disconnect pin 5
4. Solder wire between U35 pin 1 to U35 pin 12

Steps #3 and #4 will connect the AVR to IRQ1. The hack drawing is here in PDF https://drive.google.com/open?id=1rDb8PuYgx-b9c3qzr0mcGIG-kHYuz15A

**Comment by toncho11** [comment]
Thanks. 
It still requires modifying the motherboard - desoldering U53 for example. That is something I would like to avoid.

Please leave a way on github and your web-site so that people can contact you with: questions, ideas, missing links, etc. 

:)
